### ISSUE TITLE
기본 css형식을 가진 scss 파일들을 scss 문법을 사용해 리펙토링하기

### ISSUE THREAD

**Issue by wogns3623** [wogns3623/SE-Lab-Renewal#28]
* 29482f1c681efe9a0860f79e2b462deb71b2dc69 등의 커밋으로 인해 전체 디렉토리의 css들의 확장자가 scss로 바뀌었지만 코드의 구조가 변하지 않은 파일들이 있음
* 이를 scss 문법을 활용해 더 깔끔하게 바꿀 것

### Todo list
- [x] Components
    - [x] Header
        - [x] [Header.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Header.scss)
        - [x] [Logo.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Logo.scss)
        - [x] [dropdownMenu.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/component/common/menu/style/dropdownMenu.scss)
        - [x] [menu.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/component/common/menu/style/menu.scss)
    - [x]  [CourseSlide.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/CourseSlide.scss)
    - [x] [Footer.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Footer.scss)
    - [x] [Gallery.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Gallery.scss)
    - [x] [Row.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Row.scss)
    - [x] [LiveCoding.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/component/LiveCoding/style/LiveCoding.scss)
    - [x] [Slide.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Slide.scss)
    - [x] [Subject.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/Subject.scss)
- [x] Main pages
  - [x] [cse326.scss](https://github.com/wogns3623/SE-Lab-Renewal/blob/master/src/style/cse326.scss)
