### ISSUE TITLE
게시판 추가

### ISSUE THREAD

**Issue by wogns3623** [wogns3623/SE-Lab-Renewal#30]
## 게시판 기능 추가
  * 학생들끼리 의견, 코드 등을 공유하고, 공지사항을 확인하거나 과제를 제출할 수 있는 게시판 기능 추가하기

### Todo List
  - [ ] Server
    - [x] 서버에 db를 연동해 게시글을 저장할 데이터베이스 구축( #18 )

    - [ ] db 관련 api 추가
      - [ ] 사용자 정보와 함께 작성한 게시글 내용 전송
      - [ ] 각 카테고리(자유 게시판, 과제, 공지사항 등)에 따른 게시글 요청

  - [ ] Client
    - [ ] 게시글 에디터 추가
      - [ ] 기본적인 markdown 문법 지원
      - [ ] 수업 내용에 관한 토론, 의견 공유를 위한 슬라이드의 특정 페이지 링크
      - [ ] 과제 제출을 위한 파일 첨부
      - [ ] livecoding 컴포넌트 추가 가능
        - [ ] 슬라이드 livecoding 섹션에서 수정한 내용을 바로 첨부해 제출 - 슬라이드 링크 기능과 연결

    - [ ] 게시글 뷰어 추가
      - [ ] markdown 문법 해석 및 html로 변환
      - [ ] 첨부된 파일 다운로드
      - [ ] 작성자가 집적 추가하거나 슬라이드에서 링크한 livecoding 뷰어

    - [ ] 게시판
      - [ ] 카테고리별, 작성자별 등 검색 기능
  
* To be added
